// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiLwls0068lNUZ5w2ch50ZNjdOVrFYJ90',
    appId: '1:1074295281685:web:0f5b79a24db3a5e816961c',
    messagingSenderId: '1074295281685',
    projectId: 'falldetectionwebsite',
    authDomain: 'falldetectionwebsite.firebaseapp.com',
    storageBucket: 'falldetectionwebsite.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCdUFK712Dn2zHYlggcKGQkgDeHPO9ZGE',
    appId: '1:1074295281685:android:4c04ce922099927216961c',
    messagingSenderId: '1074295281685',
    projectId: 'falldetectionwebsite',
    storageBucket: 'falldetectionwebsite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAYatTkQ83kvOrI_x7XHZZw0Z-tiMZOcA',
    appId: '1:1074295281685:ios:5dadec3171bff28d16961c',
    messagingSenderId: '1074295281685',
    projectId: 'falldetectionwebsite',
    storageBucket: 'falldetectionwebsite.appspot.com',
    iosBundleId: 'com.example.fallDetectionWebAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAYatTkQ83kvOrI_x7XHZZw0Z-tiMZOcA',
    appId: '1:1074295281685:ios:5dadec3171bff28d16961c',
    messagingSenderId: '1074295281685',
    projectId: 'falldetectionwebsite',
    storageBucket: 'falldetectionwebsite.appspot.com',
    iosBundleId: 'com.example.fallDetectionWebAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiLwls0068lNUZ5w2ch50ZNjdOVrFYJ90',
    appId: '1:1074295281685:web:80e62e849e681f4516961c',
    messagingSenderId: '1074295281685',
    projectId: 'falldetectionwebsite',
    authDomain: 'falldetectionwebsite.firebaseapp.com',
    storageBucket: 'falldetectionwebsite.appspot.com',
  );
}
